import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";
import { cn } from "@/lib/utils";
import AuthProvider from "@/context/AuthProvider";
import NavBar from "@/components/NavBar";
import SideNav from "@/components/SideNav";
const outfit = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(outfit.variable, "antialiased")}>
        <AuthProvider>
          <NavBar />
          <div className="flex">
            <SideNav />
            <div className="w-full overflow-x-auto">
              <div className="overflow-auto sm:h-[calc(99vh-60px)]">
                <div className="h-[calc(100vh - 120px)] relative mx-auto flex w-full justify-center overflow-auto overflow-y-auto">
                  <div className="w-full md:max-w-7xl">{children}</div>
                </div>
              </div>
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
